### ISSUE TITLE
normalize options

### ISSUE THREAD

**Issue by CdeMills** [aphalo/photobiology#27]
Hello

the paper with DOI contains a review of several methods to express the distance between two spectra.

Its most significant contribution is IMHO to normalize an energy spectrum by its integral over the whole domain, making it a pdf. That way gives access to many methods from statistics and econometry to compare two pdfs. One of the main promising one is the
Kullback–Leibler divergence, which compare some test pdf to a reference pdf.

That divergence can be turned into a distance as

KL_distance = 0.5 * (KL(P, Q) + KL(Q, P))

where KL is the divergence computation which is available from a few R packages.

Could you please add a "pdf" option to the normalize operator ? That operation should be applied 'as is" for energy spectra, and by weighting by the wavelength for photon spectra.

Regards

Pascal

**Comment by aphalo** [comment]
@CdeMills As some people use normalization only in the case of when the value at a given wavelength is used as a reference, the operation you would like to do is implemented in function `f_scale()`. If you use `e_irrad` as argument for parameter `f` it will give the output you need, as the default is to apply the function to the whole domain and set the "summary" to 1: `range = NULL` and `target = 1`.

**Comment by CdeMills** [comment]
Hello. The DOI is 10.1016/B978-0-08-102894-0.00020-6
"Metrological hyperspectral image analysis through spectral differences", Deborah, Hilda  et al.; Hyperspectral Remote Sensing, 2020, pp 319 -- 340

Pascal
